[Bank] Fix IllegalStateException when remove bank account successfully and app show list support banks.
Add BankSupportFragment throw exception because PaymentChannelActivity is foreground while PaymentSDk return callback.

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                                                 at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1832)
                                                                                 at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1850)
                                                                                 at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:643)
                                                                                 at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:603)
                                                                                 at vn.com.vng.zalopay.bank.ui.LinkAccountFragment.initBankSupportFragment(LinkAccountFragment.java:143)
                                                                                 at vn.com.vng.zalopay.bank.ui.LinkAccountFragment.showLayoutEmpty(LinkAccountFragment.java:179)
                                                                                 at vn.com.vng.zalopay.bank.ui.LinkAccountFragment.showOrHideLayoutEmpty(LinkAccountFragment.java:171)
                                                                                 at vn.com.vng.zalopay.bank.ui.LinkAccountFragment.removeData(LinkAccountFragment.java:212)
                                                                                 at vn.com.vng.zalopay.bank.ui.LinkAccountPresenter.onRemoveAccountSuccess(LinkAccountPresenter.java:184)
                                                                                 at vn.com.vng.zalopay.bank.ui.LinkAccountPresenter.onResponseSuccessFromSDK(LinkAccountPresenter.java:172)
                                                                                 at vn.com.vng.zalopay.bank.ui.AbstractLinkCardPresenter$PaymentResponseListener.onResponseSuccess(AbstractLinkCardPresenter.java:265)
                                                                                 at vn.com.vng.zalopay.service.WalletListener.onComplete(WalletListener.java:103)
                                                                                 at vn.com.zalopay.wallet.view.component.activity.PaymentGatewayActivity.recycleActivity(PaymentGatewayActivity.java:453)
                                                                                 at vn.com.zalopay.wallet.view.component.activity.PaymentGatewayActivity.exitIfUniqueChannel(PaymentGatewayActivity.java:536)
                                                                                 at vn.com.zalopay.wallet.view.component.activity.PaymentGatewayActivity.onBackAction(PaymentGatewayActivity.java:626)
                                                                                 at vn.com.zalopay.wallet.view.component.activity.PaymentChannelActivity.lambda$new$0(PaymentChannelActivity.java:86)
                                                                                 at vn.com.zalopay.wallet.view.component.activity.PaymentChannelActivity.access$lambda$0(PaymentChannelActivity.java:0)
                                                                                 at vn.com.zalopay.wallet.view.component.activity.PaymentChannelActivity$$Lambda$1.onClick(Unknown Source)